config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = [ "public", "private", "archived" ]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: "public").count
    end
  end

  def archived?
    status == "archived"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # http_basic_authenticate_with name: "Liam", password: "123", except: [:index, :show]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end
  # redirect_to will cause the browser to make a new request, whereas render 
  # renders the specified view for the current request. It is important to use 
  # redirect_to after mutating the database or application state. Otherwise, 
  # if the user refreshes the page, the browser will make the same request, 
  # and the mutation will be repeated.
  
  def edit
    @article = Article.find(params[:id])
  end

  def update 
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end
  
  private
  
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # http_basic_authenticate_with name: "Liam", password: "123", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy 
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private 

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="edit-form">
    <%= form_with model: article, html:  {class: "edit-form"} do |form| %>
        <div>
            <%= form.label :title %><br>
            <%= form.text_field :title %>
            <% article.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>

        <div>
            <%= form.label :body %><br>
            <%= form.text_area :body %>
            <% article.errors.full_messages_for(:body).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div>
            <%= form.label :status %><br>
            <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
        </div>

        <div>
            <%= form.submit %>
        </div>
    <% end %>
</div>

app/views/articles/edit.html.erb
<div class="edit-container">
    <div class="flex-center">
        <h1>Edit Article</h1>

        <%= render "form", article: @article %>
    </div>
    <%= link_to "Back to Article", article_path(@article) %></li> 
</div>

app/views/articles/index.html.erb
<div class="wrapper">
    <div class="index-title">
        <h1>Articles</h1>
        <p>Our blog has <%= Article.public_count %> articles and counting!</p>
    </div>


    <div class="article-list flex-center">
        <% @articles.each do |article| %>
            <% unless article.archived? %>
                <div class="article-card flex-center">
                    <%= link_to article.title, article, class: "article_title" %>
                    <p><%= truncate(article.body, length: 200) %></p>
                </div>
            <% end %>
        <% end %>
        <%= link_to "New Article", new_article_path, class: "new-article" %>
    </div>
</div>

app/views/articles/new.html.erb
<div class="edit-container">    
    <div class="flex-center">
        <h1>New Article</h1>

        <%= render "form", article: @article %>
        
    </div>
    <%= link_to "Back to Articles", articles_path %></li> 
</div>

app/views/articles/show.html.erb
<div class="show-container">
  
  <div class="article-container">
    <%= link_to "All articles", articles_path %></li> 
    <div class="article-card flex-center">
      <h1><%= @article.title %></h1>

      <p><%= @article.body %></p>
    </div>

    <div class="article-edit-options">
      <%= link_to "Edit Article", edit_article_path(@article) %></li>
        
      <%= link_to "Destroy", article_path(@article), data: {
                          turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                        } %>
    </div>
  </div>
  

  <div class="comments-container">
    <h2>Comments</h2>
      <%= @article.comments.any? ? render(@article.comments) : content_tag(:p, "Nothing to show yet...", class: "no-comments") %>


    <h2>Add a comment</h2>
    <%= render "comments/form", article: @article %>
  </div>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>

    <div class="comment-card">
        <h3><%= comment.commenter %></h3>
        <p><%= comment.body %></p>
        <%= link_to "Destroy Comment", [comment.article, comment], data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    } %>
    </div>
<% end %>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.label :status %><br>
      <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="flex-center">Blog</header>
    <%= yield %>
    <%# <footer class="flex-center"></footer> %>
  </body>
</html>